# Generated by Django 3.2.4 on 2022-02-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORD_ID', models.CharField(max_length=100)),
                ('ORD_DT', models.DateField()),
            ],
        ),
    ]
